"""
Pipeline 6 — optimize-lift executor: measure PQS optimization impact at n=500.

The first atlas (score_outputs.py) answered "does the pre-flight prompt score
predict output quality?" — r=0.02 on Haiku 4.5. That is a finding about Haiku,
not about PQS. PQS's actual product is the OPTIMIZE TRANSFORM. This pipeline
tests the product thesis directly: does running a prompt through PQS
optimization produce a better OUTPUT?

For every prompt in the first atlas (outputs/atlas-general.jsonl):
  1. POST the original prompt to /api/score/full (x-pqs-internal-bypass auth).
     The endpoint returns the original prompt + score + output AND the
     Sonnet-4.6-rewritten optimized prompt + score + output (both outputs
     generated by Haiku 4.5), plus improvement_pct and an explanation.
  2. POST the optimized OUTPUT to /api/score-output (Authorization: Bearer
     auth) for a 6-dimension post-flight output score.
  3. Pull the ORIGINAL output + original output score straight from the first
     atlas row — no recompute. The first atlas already scored these.
  4. Assemble one optimize-lift row and append to OUTPUT_ABS (JSONL).

  output_lift_points = optimized_output_score.total - original_output_score.total
  prompt_lift_points = optimized_prompt_score.total - original_prompt_score.total

Headline: "Across n=500 prompts, PQS optimization lifts output quality by X
points on average."

Resumable: prompt_ids already present in OUTPUT_ABS are skipped on re-run.
Prompts are processed in parallel batches of BATCH_SIZE. First-atlas rows whose
output_score is null (generator refused in the first atlas) cannot yield an
output_lift and are skipped, logged, and counted — never written as a row.

This file does NOT modify any first-atlas file. It reads atlas-general.jsonl,
reuses load_env() from score_outputs.py, score_output_full() from cloud_judge.py,
and endpoint / auth / grade helpers from config.py.

Cost: 1 /api/score/full call per prompt (~$0.005) plus the Anthropic-side
Haiku generation the endpoint runs server-side. /api/score-output is free under
internal auth. Budget for n=500: ~$25 total.
"""
from __future__ import annotations

import json
import os
import sys
import time
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
from pathlib import Path

from config import (
    BATCH_SIZE,
    ENDPOINT_PROMPT_SCORE,
    MAX_OUTPUT_TOTAL,
    MAX_RETRIES,
    REQUEST_TIMEOUT_SEC,
    RETRY_BASE_SEC,
    ROOT,
    internal_bypass_headers,
    output_grade_from_total,
)
from cloud_judge import score_output_full
from score_outputs import load_env

# -----------------------------------------------------------------------------
# Paths + version.
# -----------------------------------------------------------------------------
PIPELINE_VERSION = "pipeline-6-optimize-lift-v1.0"

# First atlas (input — read only) and this pipeline's output.
FIRST_ATLAS_ABS = (ROOT / "scripts/pipeline-6/outputs/atlas-general.jsonl").resolve()
OUTPUT_ABS = (ROOT / "scripts/pipeline-6/outputs/atlas-optimize-lift.jsonl").resolve()

# -----------------------------------------------------------------------------
# /api/score/full — the optimize-transform endpoint.
#
# Derived from ENDPOINT_PROMPT_SCORE (".../api/score") by appending "/full", so
# it tracks PQS_PROMPT_SCORE_URL automatically. Overridable for local dev.
# Auth: x-pqs-internal-bypass header (same as /api/score). middleware.js
# validates the bypass key and skips the x402 paywall.
# -----------------------------------------------------------------------------
ENDPOINT_SCORE_FULL = os.getenv(
    "PQS_SCORE_FULL_URL", ENDPOINT_PROMPT_SCORE.rstrip("/") + "/full"
)


# -----------------------------------------------------------------------------
# /api/score/full request.
# -----------------------------------------------------------------------------
def score_full(prompt: str, vertical: str) -> dict:
    """POST a prompt to /api/score/full; return the parsed response payload.

    The payload carries `original` and `optimized` blocks (each with `prompt`,
    `score`, `output`), plus `improvement_pct` and `explanation`. Retries 5xx /
    transient errors with exponential backoff. Raises if the optimized block is
    missing an output (nothing to score downstream).
    """
    body = json.dumps({"prompt": prompt, "vertical": vertical}).encode("utf-8")
    headers = {
        "Content-Type": "application/json",
        **internal_bypass_headers(),
    }

    last_exc: Exception | None = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            req = urllib.request.Request(
                ENDPOINT_SCORE_FULL, data=body, method="POST", headers=headers,
            )
            with urllib.request.urlopen(req, timeout=REQUEST_TIMEOUT_SEC) as resp:
                payload = json.loads(resp.read().decode("utf-8"))

            # Tolerate a {data: {...}} envelope.
            if "optimized" not in payload and isinstance(payload.get("data"), dict):
                payload = payload["data"]

            optimized = payload.get("optimized") or {}
            if not (optimized.get("output") or "").strip():
                raise ValueError(
                    f"/api/score/full response missing optimized.output: "
                    f"keys={list(payload)}"
                )
            return payload
        except urllib.error.HTTPError as e:
            if e.code < 500:
                raise
            last_exc = e
        except (urllib.error.URLError, ValueError, TimeoutError) as e:
            last_exc = e

        if attempt < MAX_RETRIES:
            time.sleep(RETRY_BASE_SEC * (2 ** (attempt - 1)))

    raise RuntimeError("/api/score/full failed") from last_exc


# -----------------------------------------------------------------------------
# Score-object normalization.
# -----------------------------------------------------------------------------
def _normalize_prompt_score(raw: dict) -> dict:
    """Shape an /api/score/full optimized.score into the atlas prompt-score
    block: {total, out_of, grade, percentile, dimensions}."""
    return {
        "total": raw.get("total"),
        "out_of": raw.get("out_of", 80),
        "grade": raw.get("grade"),
        "percentile": raw.get("percentile"),
        "dimensions": raw.get("dimensions", {}),
    }


def _normalize_output_score(raw: dict) -> dict:
    """Shape an /api/score-output `score` object into the atlas output-score
    block: {total, out_of, grade, dimensions, rationales}.

    The endpoint may or may not return a grade; when absent and the scale is
    the canonical /60, derive it via output_grade_from_total."""
    total = raw.get("total")
    out_of = raw.get("out_of", MAX_OUTPUT_TOTAL)
    grade = raw.get("grade")
    if grade is None and isinstance(total, (int, float)) and out_of == MAX_OUTPUT_TOTAL:
        grade = output_grade_from_total(int(total))
    return {
        "total": total,
        "out_of": out_of,
        "grade": grade,
        "dimensions": raw.get("dimensions", {}),
        "rationales": raw.get("rationales", {}),
    }


def _lift(optimized_total, original_total):
    """optimized - original, or None if either side is missing."""
    if optimized_total is None or original_total is None:
        return None
    return optimized_total - original_total


# -----------------------------------------------------------------------------
# Optimize-lift row.
# -----------------------------------------------------------------------------
def process_prompt(fa_row: dict) -> dict:
    """Run the optimize-lift pipeline for one first-atlas row -> one atlas row.

    `fa_row` is a first-atlas (atlas-general.jsonl) row. Its prompt_score,
    output_text, and output_score are reused verbatim as the ORIGINAL side.
    Callers must pre-filter rows whose output_score is null.
    """
    prompt = fa_row["prompt_text"]
    vertical = fa_row["vertical"]

    # 1. Optimize transform — original + optimized prompt/score/output.
    full = score_full(prompt, vertical)
    optimized = full.get("optimized") or {}
    optimized_prompt = optimized.get("prompt") or ""
    optimized_output_text = optimized.get("output") or ""
    optimized_prompt_score = _normalize_prompt_score(optimized.get("score") or {})
    improvement_pct = (
        full.get("improvement_pct")
        if full.get("improvement_pct") is not None
        else full.get("improvementPct")
    )
    explanation = full.get("explanation")

    # 2. Score the optimized OUTPUT on the 6-dim post-flight rubric.
    #    score_output_full() posts {prompt, output, vertical} to /api/score-output
    #    with Authorization: Bearer auth and returns the `score` object.
    optimized_output_score = _normalize_output_score(
        score_output_full(optimized_prompt, optimized_output_text, vertical)
    )

    # 3. ORIGINAL side — reused verbatim from the first atlas.
    original_prompt_score = fa_row["prompt_score"]
    original_output_text = fa_row["output_text"]
    original_output_score = fa_row["output_score"]

    # 4. Computed lift.
    prompt_lift_points = _lift(
        optimized_prompt_score.get("total"), original_prompt_score.get("total")
    )
    output_lift_points = _lift(
        optimized_output_score.get("total"), original_output_score.get("total")
    )

    return {
        "prompt_id": fa_row["prompt_id"],
        "prompt_text": prompt,
        "vertical": vertical,

        "original_prompt_score": original_prompt_score,
        "original_output_text": original_output_text,
        "original_output_score": original_output_score,

        "optimized_prompt": optimized_prompt,
        "optimized_prompt_score": optimized_prompt_score,
        "optimized_output_text": optimized_output_text,
        "optimized_output_score": optimized_output_score,

        "prompt_lift_points": prompt_lift_points,
        "output_lift_points": output_lift_points,
        "improvement_pct": improvement_pct,
        "explanation": explanation,

        "timestamp": datetime.now(timezone.utc).isoformat(),
        "pipeline_version": PIPELINE_VERSION,
    }


# -----------------------------------------------------------------------------
# First-atlas reading + resume support.
# -----------------------------------------------------------------------------
def load_first_atlas(path: Path = FIRST_ATLAS_ABS) -> dict[str, dict]:
    """Read atlas-general.jsonl into a dict keyed by prompt_id."""
    if not path.exists():
        raise SystemExit(
            f"first atlas not found: {path}\n"
            f"Run score_outputs.py first. See scripts/pipeline-6/README.md."
        )
    rows: dict[str, dict] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        row = json.loads(line)
        rows[row["prompt_id"]] = row
    return rows


def load_done_ids(path: Path) -> set[str]:
    """prompt_ids already written to the optimize-lift atlas file."""
    if not path.exists():
        return set()
    done: set[str] = set()
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            done.add(json.loads(line)["prompt_id"])
        except (json.JSONDecodeError, KeyError):
            continue
    return done


# -----------------------------------------------------------------------------
# Runner.
# -----------------------------------------------------------------------------
def main() -> None:
    load_env()

    first_atlas = load_first_atlas()
    done = load_done_ids(OUTPUT_ABS)

    # First-atlas rows with a null output_score (first-atlas generator refusal)
    # cannot produce an output_lift — skip them up front and count separately.
    pending: list[dict] = []
    skipped_no_original: list[str] = []
    for pid, fa_row in first_atlas.items():
        if pid in done:
            continue
        if (fa_row.get("output_score") or {}).get("total") is None:
            skipped_no_original.append(pid)
            continue
        pending.append(fa_row)

    print(
        f"first atlas: {len(first_atlas)} rows | already done: {len(done)} | "
        f"skipped (no original output score): {len(skipped_no_original)} | "
        f"pending: {len(pending)}",
        file=sys.stderr,
    )
    if skipped_no_original:
        print(
            f"  skipped ids: {', '.join(skipped_no_original[:20])}"
            + (" ..." if len(skipped_no_original) > 20 else ""),
            file=sys.stderr,
        )
    if not pending:
        print("nothing to do — optimize-lift atlas already complete.",
              file=sys.stderr)
        return

    OUTPUT_ABS.parent.mkdir(parents=True, exist_ok=True)
    t0 = time.perf_counter()
    written = 0
    failures: list[tuple[str, str]] = []

    with OUTPUT_ABS.open("a", encoding="utf-8") as out:
        for batch_start in range(0, len(pending), BATCH_SIZE):
            batch = pending[batch_start:batch_start + BATCH_SIZE]
            results: dict[str, dict] = {}
            with ThreadPoolExecutor(max_workers=BATCH_SIZE) as pool:
                futures = {pool.submit(process_prompt, r): r for r in batch}
                for fut, row in futures.items():
                    try:
                        results[row["prompt_id"]] = fut.result()
                    except Exception as e:  # noqa: BLE001
                        failures.append((row["prompt_id"], repr(e)))
                        print(f"  FAILED {row['prompt_id']}: {e}", file=sys.stderr)

            # Write the batch in first-atlas order for a deterministic layout.
            for row in batch:
                atlas_row = results.get(row["prompt_id"])
                if atlas_row is None:
                    continue
                out.write(json.dumps(atlas_row, ensure_ascii=False) + "\n")
                written += 1
            out.flush()

            elapsed = time.perf_counter() - t0
            print(
                f"  progress: {written}/{len(pending)} written | "
                f"{len(failures)} failed | {elapsed/60:.1f} min elapsed",
                file=sys.stderr,
            )

    print(
        f"done: {written} optimize-lift rows appended to "
        f"{OUTPUT_ABS.relative_to(ROOT)} in {(time.perf_counter()-t0)/60:.1f} min",
        file=sys.stderr,
    )
    if failures:
        print(f"FAILURES ({len(failures)}) — re-run to retry (resumable):",
              file=sys.stderr)
        for pid, err in failures:
            print(f"  - {pid}: {err[:200]}", file=sys.stderr)
        raise SystemExit(1)


if __name__ == "__main__":
    main()
